---
title: Machine à sons
hero_image: images/banner.png
description:
  - Créer une machine à sons qui jouera des effets sonores ou de la musique à l'aide de boutons,
  - des interrupteurs ou un potentiomètre
meta_title: Projets Raspberry Pi Pico | Machine à son
meta_description: Un projet Raspberry Pi Pico pour créer une machine à sons qui joue des effets sonores à l'aide de boutons, d'interrupteurs ou d'un potentiomètre.
version: 4
listed: true
copyedit: true
last_tested: '2021-03-26'
steps:
  - title: Ce que tu vas faire
  - title: Conçois ta machine à sons
  - title: Compose tes sons
    completion:
      - engaged
  - title: Contrôle tes sons
  - title: Fabrique ton appareil
    completion:
      - internal
  - title: Questionnaire rapide
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - title: Améliorer ton projet
  - title: Partager